### ISSUE TITLE
sfhud command without toggle error

### ISSUE THREAD

**Issue by xMikux** [SchnTgaiSpock/SlimeHUD#2]
## Description (Required)
When using ``/sfhud`` without toggle will cause error.

## Steps to reproduce the Issue (Required)
1. Type ``/sfhud`` command on chat.
2. See error on console.

## Expected behavior (Required)
Should not cause error, and return some message.
(Maybe will be great if ``/sfhud toggle`` will send toggle status)

## Server Log / Error Report
https://pastebin.com/QBgM3YYZ

## Environment (Required)
![image](https://user-images.githubusercontent.com/26039249/182661887-f9831879-3b29-4497-a7ae-2ad69912d2c9.png)

**Comment by SchnTgaiSpock** [comment]
fixed in version 1.2.2 (build \#5)
