### ISSUE TITLE
Config will reset if you change the WAILA type.

### ISSUE THREAD

**Issue by MagmaSlime123** [SchnTgaiSpock/SlimeHUD#4]
## Description (Required)
Title.

## Steps to reproduce the Issue (Required)
Try changing the WAILA type from 'bossbar' to 'hotbar' in the config, then restart your server. Re-open your config.

## Expected behavior (Required)
The config to not reset and the changes to be applied.

## Server Log / Error Report
N/A

## Environment (Required)
![2022-08-21_13 02 26](https://user-images.githubusercontent.com/51277766/185806816-930248b0-87d1-40f0-9252-79e22e634431.png)
![2022-08-21_13 02 29](https://user-images.githubusercontent.com/51277766/185806817-6850ef30-1bc6-4928-acf9-ff8fbe61d37e.png)

**Comment by SchnTgaiSpock** [comment]
you need to change the config when the server isnt running, otherwise it will just save over your changes when its shutting down

**Comment by SchnTgaiSpock** [comment]
lmk if issue still persists
