### ISSUE TITLE
Tech Generators not displaying correctly

### ISSUE THREAD

**Issue by R411gun** [SchnTgaiSpock/SlimeHUD#5]
Tech Generators always show idle in bossbar, needs to be added :)

**Comment by SchnTgaiSpock** [comment]
Thanks for the report! Machines from addons often use custom code different from the core Slimefun machines so SlimeHUD can't always determine their progress/info. Addons can use the SlimeHUD API to tell SlimeHUD what to display, but that is outside of my control.

**Comment by R411gun** [comment]
Okay then I'll ask that dev to add it, thanks for the reply :)
