### ISSUE TITLE
Question/Suggestion -> Waila to vanilla blocks | MC 1.19.3

### ISSUE THREAD

**Issue by TheExotik** [SchnTgaiSpock/SlimeHUD#6]
it's possible to instead just show Slimefun blocks, the waila show also the Vanilla blocks? like dirt, cobblestone, glass...

**Comment by ybw0014** [comment]
There is an alternate plugin called WhatIsThis.

**Comment by TheExotik** [comment]
i know that but i just said this cause is better have just one showing all than have 2 showing one thing you know... but that's ok thank you ^^
