### ISSUE TITLE
How it Works? Bossbar does not appear!

### ISSUE THREAD

**Issue by wpmidia** [SchnTgaiSpock/SlimeHUD#7]
## Description (Required)
I added the plugin in the /plugins folder, started the server and nothing changed! When passing near the machines, the bossbar does not appear. what did I do wrong?

## Steps to reproduce the Issue (Required)
I added the plugin in the /plugins folder, started the server 

## Expected behavior (Required)
The machine name should appear in the bossbar ... (Right?)

## Environment (Required)
- Minecraft 1.20.1
- SlimeHUD v1.2.7
- Slimefun DEV - 1087
- Paper-64 - 1.20.1-R0.1-SNAPSHOT

**Comment by SchnTgaiSpock** [comment]
> Server Log / Error Report

please provide this
